### ISSUE TITLE
Python 3 compatibility 

### ISSUE THREAD

**Issue by srikris** [dato-code/SFrame#16] opened 2015-09-19 23:47 UTC
The package currently only supports Python 2.7x.

**Comment by ylow** [comment] 2015-09-22 00:08
This should not be difficult I think...

**Comment by ylow** [comment] 2015-09-25 20:15
I know relatively little about Python 2-3 porting. But I suspect it is not hard. The greatest concerns are with two bits
1. the pickling code (cloudpickle) 
2. partial python decompiler which is used to optimize lambdas of native functions. (i.e. sarray.apply(lambda x: gl.extensions.something(x). where in this case it forward entirely in C++ without going through Python)

**Comment by TobyRoseman** [comment] 2015-10-20 20:55
I'm been working on Python 3 support. For those interested, checkout the "python3" branch on this repo.

I'm managed to build the dependencies (I'll put that up for code review soon and we'll open source that build). I fixed a lot of, mostly straight forward, issues and can now import sframe from python 3. I'm currently tracking down several issues in the cython layer.

**Comment by stonebig** [comment] 2016-01-09 13:48
any progress ?

**Comment by stonebig** [comment] 2016-01-11 17:27
no progress ?

**Comment by esamanas** [comment] 2016-01-11 19:03
Hi @stonebig,

We're still working on this. As Toby posted, you can check the "python3" branch on the SFrame repo for updates. The last commit was just a few days ago.

This effort is taking longer than perhaps a typical Python package's migration to python 3 support because we are not a pure Python package. I haven't been directly involved in this effort, but hearing Toby's updates, it seems most of the complexity is with the differing C interface to Python 3.

I'm happy to see that you have interest in this, and I hope it's worth the wait!

**Comment by stonebig** [comment] 2016-01-11 20:19
I understand the complexity. Thank you for the update.

**Comment by alvations** [comment] 2016-01-21 16:12
+1 on Python 3 port, how could we (public contributors) help if you require help in porting process?

**Comment by TobyRoseman** [comment] 2016-01-22 00:26
@alvations - Thanks for your offer to help! 

The current changes necessary are relatively deep and monolithic. It's hard to do development of it in parallel, but we expect to achieve basic Python3 functionality *very soon* and it will be helpful to get some feedback and help after that. It would be great if the community could help us beta test it. 

For those really interested, my current changes can be found in the `python3-merge` branch.

**Comment by hoytak** [comment] 2016-02-01 18:21
@alvations, @stonebig:  As an update to all of you tracking this development -- we have finally implemented all the changes needed for everything to work with both python 2 and python 3.  The current pull request to incorporate these changes is https://github.com/dato-code/SFrame/pull/156, which also includes https://github.com/dato-code/SFrame/pull/132 (132 will be merged first).  We are now running a number of checks and benchmarks on these two pull requests before merging them in, but we should have python 3 support in master shortly!

**Comment by ylow** [comment] 2016-02-01 18:22
Is the python3 branch up to date if I want to try to build it myself?

**Comment by TobyRoseman** [comment] 2016-02-01 18:34
@ylow - Hoyta recently merged the Python3 changes with his boost python removal. You can this all together in his `python3-and-boost-removal-and-hypersquirrels` in [Hoyta's fork](https://github.com/hoytak/SFrame)

**Comment by alvations** [comment] 2016-02-01 18:39
@hoytak Thanks for the update! Would the `graphlab-create` version of SFrame work on python2 and python3?

**Comment by TobyRoseman** [comment] 2016-02-02 22:31
@alvations - The code will work in both Python2 and Python3. However we will still have different wheels/eggs for Python2 and Python3 because the generated Cython code will have to be different.

**Comment by alvations** [comment] 2016-02-11 20:50
@TobyRoseman A quick thing to note, somehow `pip` for python3 is allowing me to do install but it's still using the old code:

```
alvas@ubi:~$ sudo pip3 install sframe
Collecting sframe
  Downloading SFrame-1.8.tar.gz (20.4MB)
    100% |████████████████████████████████| 20.4MB 22kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c3oymagz/sframe/setup.py", line 83
        print ""
               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c3oymagz/sframe
```

**Comment by TobyRoseman** [comment] 2016-02-11 21:49
Thanks @alvations for the heads up. This is a known issue. It caused because on Linux we don't embed the python version in the egg file name. The issue is fixed in the current Python3 pull request.

**Comment by TobyRoseman** [comment] 2016-02-17 01:27
@alvations @stonebig - I'm happy to announce a beta release with Python 3 support!

To try it out in Python 3, download the file below for your operating system and run:
`pip install -U <path to downloaded file>`

[Linux SFrame Python3](https://s3.amazonaws.com/static.dato.com/files/sframe/SFrame-1.9-py3.4.tar.gz)
[Windows SFrame Python3](https://s3.amazonaws.com/static.dato.com/files/sframe/SFrame-1.9-cp34-none-win_amd64.whl)
[Mac OS X SFrame Python3](https://s3.amazonaws.com/static.dato.com/files/sframe/SFrame-1.9-cp34-cp34m-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.macosx_10_11_x86_64.macosx_10_11_intel.whl)

These files were built from commit   `8133577755b269e034b4a0419b995ea7e8811571`

Please give it a try and let me know if you find any issues.

**Comment by stonebig** [comment] 2016-02-17 17:02
just publish them as 1.9b1 on pypi

**Comment by alvations** [comment] 2016-02-17 17:45
@TobyRoseman Currently, it will only work on python3.4 ? Or it does work on python3.5 too, I just need to ignore the warnings:

```
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sframe
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_unity' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_ipc' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_sarray' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_sframe' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_flexible_type' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_cpp_utils' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_dataframe' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_graph' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_model' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_variant' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_server' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_sketch' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_sarray_builder' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'sframe.cython.cy_sframe_builder' does not match runtime version 3.5
  return f(*args, **kwds)
```

**Comment by alvations** [comment] 2016-02-17 17:59
@TobyRoseman It looks great! Now I can do threaded text processing without really coding the multi-threading for my functions:

```python
>>> import sframe
>>> import time
>>> from nltk import word_tokenize
>>> 
>>> import urllib.request
>>> url = 'https://raw.githubusercontent.com/Simdiva/DSL-Task/master/data/DSLCC-v2.0/test/test.txt'
>>> response = urllib.request.urlopen(url)
>>> data = response.read().decode('utf8')
>>> 
>>> for _ in range(10):
...     start = time.time()
...     for line in data.split('\n'):
...         x = word_tokenize(line)
...     print ('word_tokenize():\t', time.time() - start)
... 
word_tokenize():	 4.058445692062378
word_tokenize():	 4.05820369720459
word_tokenize():	 4.090051174163818
word_tokenize():	 4.210559129714966
word_tokenize():	 4.17473030090332
word_tokenize():	 4.105806589126587
word_tokenize():	 4.082665681838989
word_tokenize():	 4.13646936416626
word_tokenize():	 4.185062408447266
word_tokenize():	 4.085020065307617

>>> sf = sframe.SFrame(data.split('\n'))
>>> for _ in range(10):
...     start = time.time()
...     x = list(sf.apply(lambda x: word_tokenize(x['X1'])))
...     print ('word_tokenize() with sframe:\t', time.time() - start)
... 
word_tokenize() with sframe:	 7.174573659896851
word_tokenize() with sframe:	 5.072867393493652
word_tokenize() with sframe:	 5.129574775695801
word_tokenize() with sframe:	 5.10952091217041
word_tokenize() with sframe:	 5.015898942947388
word_tokenize() with sframe:	 5.037845611572266
word_tokenize() with sframe:	 5.015375852584839
word_tokenize() with sframe:	 5.016635894775391
word_tokenize() with sframe:	 5.155989170074463
word_tokenize() with sframe:	 5.132697105407715

>>> for _ in range(10):
...     start = time.time()
...     x = [word_tokenize(line) for line in data.split('\n')]
...     print ('str.split():\t', time.time() - start)
... 
str.split():	 4.176181793212891
str.split():	 4.116339921951294
str.split():	 4.1104896068573
str.split():	 4.140819549560547
str.split():	 4.103625774383545
str.split():	 4.125757694244385
str.split():	 4.10755729675293
str.split():	 4.177418947219849
str.split():	 4.11145281791687
str.split():	 4.140623092651367
```

I understand that the speed difference might be because I have something else running on the other cores. But given a much larger dataset and dedicated cores, I can really see this scale =)

Thanks for the Python3 port!!

**Comment by TobyRoseman** [comment] 2016-02-17 18:00
@alvations - We've currently only tested it on 3.4. I tried to get it working with 3.5 a few months ago but, at least at that time, most of our package dependencies didn't support 3.5.

**Comment by TobyRoseman** [comment] 2016-03-17 23:14
SFrames for Python 3.4 can now be installed via pip. Python 3.5 support is coming soon.

**Comment by ZelphirKaltstahl** [comment] 2016-04-17 11:03
> @alvations @stonebig - I'm happy to announce a beta release with Python 3 support!
> 
> To try it out in Python 3, download the file below for your operating system and run:
> pip install -U <path to downloaded file>

> Linux SFrame Python3
> Windows SFrame Python3
> Mac OS X SFrame Python3

> These files were built from commit 8133577755b269e034b4a0419b995ea7e8811571

> Please give it a try and let me know if you find any issues.

Unfortunately this doesn't work:

`Processing ./SFrame-1.9-py3.4.tar.gz
Exception:
Traceback (most recent call last):
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1634, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1610, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1475, in __init__
    self.firstmember = self.next()
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 2283, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1087, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<?')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/download.py", line 798, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/download.py", line 705, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/utils/__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/site-packages/pip/utils/__init__.py", line 538, in untar_file
    tar = tarfile.open(filename, mode)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1580, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/xiaolong/development/anaconda3/envs/coursera_ml_classification/lib/python3.5/tarfile.py", line 1638, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file`

**Comment by TobyRoseman** [comment] 2016-04-18 19:36
@ZelphirKaltstahl - It looks like you're using Python 3.5, we don't support that yet, but it's coming soon.

**Comment by TobyRoseman** [comment] 2016-06-21 17:41
@ZelphirKaltstahl - We now have beta support for 3.5 for both SFrame and GraphLab Create, see: https://dato.com/download/release-notes.html

**Closed by TobyRoseman** 2016-06-21 17:41 UTC
Labels: enhancement

**Comment by ZelphirKaltstahl** [comment] 2016-07-28 20:41
@TobyRoseman Hi, I just found this again. Was SFrame separately removed? I cannot find it separately on [https://dato.com/download/release-notes.html](https://dato.com/download/release-notes.html) anymore =(
